---
abstract: 'Stackable Plack authentication'
author:
  - 'Copyright 2011 Ben Morrow <ben@morrow.me.uk>.'
build_requires:
  Test::More: 0.65
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-AuthN+Z
provides:
  Plack::Middleware::AuthN:
    file: lib/Plack/Middleware/AuthN.pm
    version: 1
  Plack::Middleware::AuthN::Basic:
    file: lib/Plack/Middleware/AuthN/Basic.pm
    version: 1
  Plack::Middleware::AuthZ::RequireUser:
    file: lib/Plack/Middleware/AuthZ/RequireUser.pm
    version: 1
requires:
  MIME::Base64: 0
  Plack: 0
  Scalar::Util: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 1
